replicaCount: 2

image:
  repository: 499000782465.dkr.ecr.us-east-1.amazonaws.com/clubhub
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: clubhub.com
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: ""
  automount: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
